import { createApp } from 'vue';
import { createI18n } from 'vue-i18n';
import App from './App.vue';
import './style.css';

const languageMap = {
  en: 'en',
  zh: 'zh',
  it: 'it',
  es: 'es',
  hmn: 'hmn',
  ja: 'ja',
  jp: 'ja',
};

function normalizeLocale(language) {
  return languageMap[language?.toLowerCase().split('-')[0]] || '';
}

const savedLanguage = localStorage.getItem('preferredLanguage');
const browserLanguage = (navigator.languages || [navigator.language])
  .map(normalizeLocale)
  .find(Boolean);
const initialLocale = normalizeLocale(savedLanguage) || browserLanguage || 'en';

const messages = {
  en: {
    metaTitle: "Here's Mars",
    langName: 'English',
    availability: 'Online for kind humans',
    eyebrow: 'contact://maoawa',
    introLines: ['Hi,', "I'm Mars"],
    introLineBefore: 'Also Marshall or',
    introLineAfter: '',
    primaryTitle: 'Best ways to reach me',
    primarySubtitle: 'Start here if you just want to say hi.',
    chooseLanguage: 'Language',
    open: 'Open',
    protectedHint: 'Tap to open',
    showQr: 'Show QR',
    hideQr: 'Hide QR',
    terminalCaption: 'tiny terminal',
    terminalLines: [
      'booting contact card',
      'loading safe routes',
      'checking visitor intent',
      'contact handlers ready',
      'public links filtered',
      'visitor-friendly mode on',
    ],
    aboutTitle: 'A little about me',
    aboutBody: 'I am a 17-year-old student, beginner programmer, and language learner. I like tech, foreign cultures, photography, gaming, music, and meeting friends from different places.',
    projectsTitle: 'My projects',
    projectsSubtitle: 'A few places I keep memories, writing, and experiments.',
    moreTitle: 'More places',
    mainlandTitle: 'Mainland China',
    footerRepo: 'This website is open source on GitHub under the AGPL license.',
    footerUpdated: 'Updated on July 7, 2026',
    footerMirror: 'Cloudflare Pages mirror',
    legal: 'moeICP No.20235320',
    qrAlt: 'WeChat QR code',
    contacts: {
      imessage: { label: 'iMessage', detail: 'Best for Apple devices' },
      telegram: { label: 'Telegram', detail: 'Fast international chat' },
      discord: { label: 'Discord', detail: 'Gaming and communities' },
      email: { label: 'Email', detail: 'Good for longer messages' },
      github: { label: 'GitHub', detail: 'Code and projects' },
      wechat: { label: 'WeChat', detail: 'Mainland China chat' },
      qq: { label: 'QQ', detail: 'Classic CN messenger' },
      bilibili: { label: 'Bilibili', detail: 'Videos and profile' },
      phone: { label: '🇨🇳 CN phone', detail: 'Mainland China number' },
      phoneUs: { label: '🇺🇸 US phone', detail: 'North America number' },
      phoneUk: { label: '🇬🇧 UK phone', detail: 'Europe number' },
      x: { label: 'X / Twitter', detail: 'Social updates' },
      instagram: { label: 'Instagram', detail: 'Photos and life' },
      tiktok: { label: 'TikTok', detail: 'Short videos' },
      steam: { label: 'Steam', detail: 'Games' },
    },
    projects: {
      vrchat: { label: 'VRChat Gallery', detail: 'Recording cherished moments with my friends in VRChat.' },
      cnBlog: { label: 'Chinese Blog', detail: 'Longer writing and notes in Chinese.' },
      enBlog: { label: 'English Blog', detail: 'English writing, thoughts, and updates.' },
    },
  },
  zh: {
    metaTitle: '这里是毛毛',
    langName: '简体中文',
    availability: '欢迎友好的人类访问',
    eyebrow: 'contact://maoawa',
    introLines: ['你好，', '我是毛毛'],
    introLineBefore: '也可以叫我 Mars、Marshall 或',
    introLineAfter: '',
    primaryTitle: '优先联系方式',
    primarySubtitle: '只是想打个招呼的话，从这里开始就好。',
    chooseLanguage: '语言',
    open: '打开',
    protectedHint: '点按打开',
    showQr: '显示二维码',
    hideQr: '隐藏二维码',
    terminalCaption: '小终端',
    terminalLines: [
      '正在启动联系卡片',
      '正在加载安全路线',
      '正在确认访客意图',
      '联系处理器已就绪',
      '公开链接已过滤',
      '访客友好模式开启',
    ],
    aboutTitle: '关于我',
    aboutBody: '我是 17 岁的学生、菜鸟程序员，也在学习语言。我喜欢科技、外国文化、摄影、游戏、音乐，也喜欢认识来自不同地方的朋友。',
    projectsTitle: '我的项目',
    projectsSubtitle: '这里放着我的回忆、文字和一些小实验。',
    moreTitle: '更多平台',
    mainlandTitle: '中国大陆',
    footerRepo: '这个网站以 AGPL 许可证开源在 GitHub。',
    footerUpdated: '更新于 2026 年 7 月 7 日',
    footerMirror: 'Cloudflare Pages 镜像站',
    legal: '萌ICP备20235320',
    qrAlt: '微信二维码',
    contacts: {
      imessage: { label: 'iMessage 信息', detail: '适合 Apple 设备' },
      telegram: { label: 'Telegram', detail: '国际聊天比较快' },
      discord: { label: 'Discord', detail: '游戏和社区' },
      email: { label: '邮箱', detail: '适合长一点的消息' },
      github: { label: 'GitHub', detail: '代码和项目' },
      wechat: { label: '微信', detail: '中国大陆常用聊天' },
      qq: { label: 'QQ', detail: '经典聊天工具' },
      bilibili: { label: '哔哩哔哩', detail: '视频和主页' },
      phone: { label: '🇨🇳 中国大陆电话', detail: '中国大陆号码' },
      phoneUs: { label: '🇺🇸 美国电话', detail: '北美号码' },
      phoneUk: { label: '🇬🇧 英国电话', detail: '欧洲号码' },
      x: { label: 'X / Twitter', detail: '社交动态' },
      instagram: { label: 'Instagram', detail: '照片和生活' },
      tiktok: { label: 'TikTok', detail: '短视频' },
      steam: { label: 'Steam', detail: '游戏' },
    },
    projects: {
      vrchat: { label: 'VRChat 相册', detail: '记录我和朋友们在 VRChat 里的珍贵时刻。' },
      cnBlog: { label: '中文博客', detail: '我的中文长文、随笔和记录。' },
      enBlog: { label: '英文博客', detail: '英文写作、想法和近况。' },
    },
  },
  it: {
    metaTitle: 'Qui Mars',
    langName: 'Italiano',
    availability: 'Online per persone gentili',
    eyebrow: 'contact://maoawa',
    introLines: ['Ciao,', 'sono Mars'],
    introLineBefore: 'Anche Marshall o',
    introLineAfter: '',
    primaryTitle: 'Modi migliori per contattarmi',
    primarySubtitle: 'Inizia qui se vuoi solo salutare.',
    chooseLanguage: 'Lingua',
    open: 'Apri',
    protectedHint: 'Tocca per aprire',
    showQr: 'Mostra QR',
    hideQr: 'Nascondi QR',
    terminalCaption: 'mini terminale',
    terminalLines: [
      'avvio scheda contatti',
      'carico percorsi sicuri',
      'controllo intento visitatore',
      'handler contatti pronti',
      'link pubblici filtrati',
      'modalita semplice attiva',
    ],
    aboutTitle: 'Un po di me',
    aboutBody: 'Ho 17 anni, sono studente, programmatore principiante e studio lingue. Mi piacciono tecnologia, culture straniere, fotografia, videogiochi, musica e conoscere amici da posti diversi.',
    projectsTitle: 'I miei progetti',
    projectsSubtitle: 'Alcuni posti dove tengo ricordi, scritti ed esperimenti.',
    moreTitle: 'Altri posti',
    mainlandTitle: 'Cina continentale',
    footerRepo: 'Questo sito e open source su GitHub con licenza AGPL.',
    footerUpdated: 'Aggiornato il 7 luglio 2026',
    footerMirror: 'Mirror Cloudflare Pages',
    legal: 'moeICP No.20235320',
    qrAlt: 'Codice QR WeChat',
    contacts: {
      imessage: { label: 'iMessage', detail: 'Ideale per dispositivi Apple' },
      telegram: { label: 'Telegram', detail: 'Chat internazionale rapida' },
      discord: { label: 'Discord', detail: 'Giochi e community' },
      email: { label: 'Email', detail: 'Per messaggi piu lunghi' },
      github: { label: 'GitHub', detail: 'Codice e progetti' },
      wechat: { label: 'WeChat', detail: 'Chat in Cina continentale' },
      qq: { label: 'QQ', detail: 'Messenger classico cinese' },
      bilibili: { label: 'Bilibili', detail: 'Video e profilo' },
      phone: { label: '🇨🇳 Telefono CN', detail: 'Numero in Cina continentale' },
      phoneUs: { label: '🇺🇸 Telefono USA', detail: 'Numero Nord America' },
      phoneUk: { label: '🇬🇧 Telefono UK', detail: 'Numero Europa' },
      x: { label: 'X / Twitter', detail: 'Aggiornamenti social' },
      instagram: { label: 'Instagram', detail: 'Foto e vita' },
      tiktok: { label: 'TikTok', detail: 'Video brevi' },
      steam: { label: 'Steam', detail: 'Giochi' },
    },
    projects: {
      vrchat: { label: 'Galleria VRChat', detail: 'Momenti preziosi con i miei amici in VRChat.' },
      cnBlog: { label: 'Blog cinese', detail: 'Scritti e appunti piu lunghi in cinese.' },
      enBlog: { label: 'Blog inglese', detail: 'Scritti, pensieri e aggiornamenti in inglese.' },
    },
  },
  ja: {
    metaTitle: 'Mars です',
    langName: '日本語',
    availability: 'やさしい人向けにオンライン',
    eyebrow: 'contact://maoawa',
    introLines: ['こんにちは、', 'Mars です'],
    introLineBefore: 'Marshall または',
    introLineAfter: 'とも呼ばれます',
    primaryTitle: '連絡しやすい場所',
    primarySubtitle: 'まずはここからどうぞ。',
    chooseLanguage: '言語',
    open: '開く',
    protectedHint: 'タップして開く',
    showQr: 'QRを表示',
    hideQr: 'QRを隠す',
    terminalCaption: '小さなターミナル',
    terminalLines: [
      '連絡カードを起動中',
      '安全なルートを読み込み中',
      '訪問者の意図を確認中',
      '連絡ハンドラ準備完了',
      '公開リンクをフィルタ済み',
      'やさしい表示モード',
    ],
    aboutTitle: '自己紹介',
    aboutBody: '17歳の学生で、初心者プログラマー、言語学習者です。テック、海外文化、写真、ゲーム、音楽、いろいろな場所の友達と出会うことが好きです。',
    projectsTitle: '私のプロジェクト',
    projectsSubtitle: '思い出、文章、小さな実験を置いている場所です。',
    moreTitle: 'ほかの場所',
    mainlandTitle: '中国本土',
    footerRepo: 'このサイトは AGPL ライセンスで GitHub に公開されています。',
    footerUpdated: '2026年7月7日 更新',
    footerMirror: 'Cloudflare Pages ミラー',
    legal: 'moeICP No.20235320',
    qrAlt: 'WeChat QRコード',
    contacts: {
      imessage: { label: 'iMessage', detail: 'Apple デバイス向け' },
      telegram: { label: 'Telegram', detail: '海外チャットに便利' },
      discord: { label: 'Discord', detail: 'ゲームとコミュニティ' },
      email: { label: 'メール', detail: '長めの連絡に便利' },
      github: { label: 'GitHub', detail: 'コードとプロジェクト' },
      wechat: { label: 'WeChat', detail: '中国本土の連絡' },
      qq: { label: 'QQ', detail: '中国の定番メッセンジャー' },
      bilibili: { label: 'Bilibili', detail: '動画とプロフィール' },
      phone: { label: '🇨🇳 中国電話', detail: '中国本土の番号' },
      phoneUs: { label: '🇺🇸 米国電話', detail: '北米の番号' },
      phoneUk: { label: '🇬🇧 英国電話', detail: '欧州の番号' },
      x: { label: 'X / Twitter', detail: 'SNS の更新' },
      instagram: { label: 'Instagram', detail: '写真と日常' },
      tiktok: { label: 'TikTok', detail: '短い動画' },
      steam: { label: 'Steam', detail: 'ゲーム' },
    },
    projects: {
      vrchat: { label: 'VRChat ギャラリー', detail: 'VRChat で友達と過ごした大切な瞬間を記録しています。' },
      cnBlog: { label: '中国語ブログ', detail: '中国語の長文、メモ、記録。' },
      enBlog: { label: '英語ブログ', detail: '英語の文章、考え、近況。' },
    },
  },
  es: {
    metaTitle: 'Aqui esta Mars',
    langName: 'Espanol',
    availability: 'Online para personas amables',
    eyebrow: 'contact://maoawa',
    introLines: ['Hola,', 'soy Mars'],
    introLineBefore: 'Tambien Marshall o',
    introLineAfter: '',
    primaryTitle: 'Mejores formas de contactarme',
    primarySubtitle: 'Empieza aqui si solo quieres saludar.',
    chooseLanguage: 'Idioma',
    open: 'Abrir',
    protectedHint: 'Toca para abrir',
    showQr: 'Mostrar QR',
    hideQr: 'Ocultar QR',
    terminalCaption: 'mini terminal',
    terminalLines: [
      'iniciando tarjeta de contacto',
      'cargando rutas seguras',
      'revisando intencion visitante',
      'contactos listos',
      'enlaces publicos filtrados',
      'modo facil activado',
    ],
    aboutTitle: 'Un poco sobre mi',
    aboutBody: 'Soy estudiante de 17 anos, programador principiante y estudiante de idiomas. Me gustan la tecnologia, las culturas extranjeras, la fotografia, los videojuegos, la musica y conocer amigos de distintos lugares.',
    projectsTitle: 'Mis proyectos',
    projectsSubtitle: 'Algunos lugares donde guardo recuerdos, textos y experimentos.',
    moreTitle: 'Mas lugares',
    mainlandTitle: 'China continental',
    footerRepo: 'Este sitio es de codigo abierto en GitHub bajo la licencia AGPL.',
    footerUpdated: 'Actualizado el 7 de julio de 2026',
    footerMirror: 'Mirror de Cloudflare Pages',
    legal: 'moeICP No.20235320',
    qrAlt: 'Codigo QR de WeChat',
    contacts: {
      imessage: { label: 'iMessage', detail: 'Mejor para dispositivos Apple' },
      telegram: { label: 'Telegram', detail: 'Chat internacional rapido' },
      discord: { label: 'Discord', detail: 'Juegos y comunidades' },
      email: { label: 'Email', detail: 'Bueno para mensajes largos' },
      github: { label: 'GitHub', detail: 'Codigo y proyectos' },
      wechat: { label: 'WeChat', detail: 'Chat en China continental' },
      qq: { label: 'QQ', detail: 'Mensajeria clasica china' },
      bilibili: { label: 'Bilibili', detail: 'Videos y perfil' },
      phone: { label: '🇨🇳 Telefono CN', detail: 'Numero de China continental' },
      phoneUs: { label: '🇺🇸 Telefono de EE. UU.', detail: 'Numero de Norteamerica' },
      phoneUk: { label: '🇬🇧 Telefono del Reino Unido', detail: 'Numero de Europa' },
      x: { label: 'X / Twitter', detail: 'Actualizaciones sociales' },
      instagram: { label: 'Instagram', detail: 'Fotos y vida' },
      tiktok: { label: 'TikTok', detail: 'Videos cortos' },
      steam: { label: 'Steam', detail: 'Juegos' },
    },
    projects: {
      vrchat: { label: 'Galeria de VRChat', detail: 'Momentos preciados con mis amigos en VRChat.' },
      cnBlog: { label: 'Blog chino', detail: 'Textos y notas mas largas en chino.' },
      enBlog: { label: 'Blog ingles', detail: 'Textos, ideas y novedades en ingles.' },
    },
  },
  hmn: {
    metaTitle: 'Nov yog Mars',
    langName: 'Hmoob',
    availability: 'Qhib rau cov neeg siab zoo',
    eyebrow: 'contact://maoawa',
    introLines: ['Nyob zoo,', 'Kuv yog Mars'],
    introLineBefore: 'Kuj hu kuv ua Marshall lossis',
    introLineAfter: '',
    primaryTitle: 'Txoj kev zoo tshaj los tiv tauj kuv',
    primarySubtitle: 'Pib ntawm no yog tias koj tsuas xav hais nyob zoo',
    chooseLanguage: 'Lus',
    open: 'Qhib',
    protectedHint: 'Nias kom qhib',
    showQr: 'Qhia QR',
    hideQr: 'Zais QR',
    terminalCaption: 'Lub davhlau ya nyob twg me',
    terminalLines: [
      'tab tom pib daim npav tiv tauj',
      'tab tom rub cov kev ruaj ntseg',
      'tab tom xyuas tus qhua lub hom phiaj',
      'cov cuab yeej tiv tauj npaj txhij lawm',
      'cov txuas pej xeem raug lim lawm',
      'hom phooj ywg rau qhua qhib lawm',
    ],
    aboutTitle: 'Me ntsis txog kuv',
    aboutBody: 'Kuv yog ib tug tub kawm ntawv muaj 17 xyoos, yog ib tug pib kawm sau program thiab kawm lus. Kuv nyiam technology, lwm haiv neeg kab lis kev cai, thaij duab, ua si, suab paj nruag thiab ntsib phooj ywg los ntawm ntau qhov chaw.',
    projectsTitle: 'Kuv cov project',
    projectsSubtitle: 'Ob peb qhov chaw uas kuv khaws kev nco, ntawv sau thiab kev sim.',
    moreTitle: 'Lwm qhov chaw',
    mainlandTitle: 'Suav Teb Av Loj',
    footerRepo: 'Lub website no yog open source hauv GitHub raws li daim ntawv tso cai AGPL.',
    footerUpdated: 'Hloov tshiab rau Lub Xya Hli 7, 2026',
    footerMirror: 'Cloudflare Pages daim mirror',
    legal: 'moeICP No.20235320',
    qrAlt: 'WeChat QR code',
    contacts: {
      imessage: { label: 'iMessage', detail: 'Zoo tshaj rau Apple devices' },
      telegram: { label: 'Telegram', detail: 'Sib tham thoob ntiaj teb ceev' },
      discord: { label: 'Discord', detail: 'Games thiab communities' },
      email: { label: 'Email', detail: 'Zoo rau cov lus ntev dua' },
      github: { label: 'GitHub', detail: 'Code thiab projects' },
      wechat: { label: 'WeChat', detail: 'Sib tham hauv Suav Teb Av Loj' },
      qq: { label: 'QQ', detail: 'Messenger Suav qub' },
      bilibili: { label: 'Bilibili', detail: 'Videos thiab profile' },
      phone: { label: '🇨🇳 Xov tooj Suav', detail: 'Tus xov tooj Suav Teb Av Loj' },
      phoneUs: { label: '🇺🇸 Xov tooj Asmeskas', detail: 'Tus xov tooj North America' },
      phoneUk: { label: '🇬🇧 Xov tooj Askiv', detail: 'Tus xov tooj Europe' },
      x: { label: 'X / Twitter', detail: 'Social updates' },
      instagram: { label: 'Instagram', detail: 'Duab thiab lub neej' },
      tiktok: { label: 'TikTok', detail: 'Videos luv' },
      steam: { label: 'Steam', detail: 'Games' },
    },
    projects: {
      vrchat: { label: 'VRChat Gallery', detail: 'Khaws cov sijhawm muaj nqis nrog kuv cov phooj ywg hauv VRChat.' },
      cnBlog: { label: 'Blog lus Suav', detail: 'Ntawv sau ntev thiab notes ua lus Suav.' },
      enBlog: { label: 'Blog lus Askiv', detail: 'Ntawv sau, kev xav thiab xov tshiab ua lus Askiv.' },
    },
  },
};

const i18n = createI18n({
  legacy: false,
  locale: initialLocale,
  fallbackLocale: 'en',
  messages,
});

createApp(App).use(i18n).mount('#app');
